import {useMemo,useState} from "react";
import "./styles.css";
type Key="TWD"|"FTWD"|"TALES"|"WB"|"OWL"|"DARYL"|"DEAD";
const S:Record<Key,{name:string;color:string;short:string}>={
TWD:{name:"The Walking Dead",color:"#e5e8e8",short:"TWD"},FTWD:{name:"Fear the Walking Dead",color:"#d7a84b",short:"Fear"},
TALES:{name:"Tales of the Walking Dead",color:"#d88468",short:"Tales"},WB:{name:"World Beyond",color:"#75a9c7",short:"World Beyond"},
OWL:{name:"The Ones Who Live",color:"#d16d68",short:"TOWL"},DARYL:{name:"Daryl Dixon",color:"#a08ac7",short:"Daryl"},DEAD:{name:"Dead City",color:"#5eb39a",short:"Dead City"}};
const L=[["Atlanta",33.75,-84.39,"TWD",2010,"City","The flagship story opens here."],["King County",34.22,-84.55,"TWD",2010,"Town","Rick's home county and an early Morgan connection."],["Los Angeles",34.05,-118.24,"FTWD",2010,"City","Fear begins during the initial outbreak."],["San Diego",32.72,-117.16,"FTWD",2010,"City","An early Southern California node."],["Baja California",31,-115,"FTWD",2011,"Region","The Fear group reaches Mexico."],["Alexandria",38.8,-77.05,"TWD",2014,"Community","A central long-term flagship community."],["Hilltop",38,-77.3,"TWD",2016,"Community","A major allied community."],["Kingdom",38.2,-77,"TWD",2016,"Community","Ezekiel's community."],["Sanctuary",38.7,-77.2,"TWD",2015,"Stronghold","The Saviors' headquarters."],["Omaha",41.26,-95.93,"WB",2020,"Community","A Civic Republic settlement."],["Philadelphia",39.95,-75.16,"OWL",2024,"City","The CRM's Philadelphia operation."],["France",46.2,2.2,"DARYL",2023,"Country","Daryl's European branch."],["Paris",48.86,2.35,"DARYL",2023,"City","A major European destination."],["Spain",40.42,-3.7,"DARYL",2025,"Country","The European storyline extends here."],["Manhattan",40.78,-73.97,"DEAD",2024,"City","Maggie and Negan enter Manhattan."],["Commonwealth",40.8,-81.9,"TWD",2025,"Community","The flagship's final major community arc."]] as const;
const E=[[2010,"Fear S1 — Los Angeles","FTWD"],[2010,"TWD S1 — Atlanta","TWD"],[2011,"TWD S2 — The farm","TWD"],[2012,"TWD S3 — Prison / Woodbury","TWD"],[2014,"TWD S5–6 — Alexandria","TWD"],[2016,"TWD S6–7 — Saviors","TWD"],[2017,"TWD S8 — All Out War","TWD"],[2017,"Fear S4 — Morgan crossover","FTWD"],[2018,"TWD S9 — Rick's disappearance","TWD"],[2020,"World Beyond — CRM","WB"],[2023,"Daryl Dixon — France","DARYL"],[2024,"The Ones Who Live — Philadelphia","OWL"],[2024,"Dead City — Manhattan","DEAD"],[2025,"Daryl Dixon — Spain","DARYL"]] as const;
const project=(lat:number,lng:number)=>({x:(lng+180)/360*100,y:(90-lat)/180*100});
export default function App(){
 const [series,setSeries]=useState<Key|"ALL">("ALL"),[year,setYear]=useState(2010),[q,setQ]=useState(""),[selected,setSelected]=useState<number|null>(null),[view,setView]=useState("map");
 const visible=useMemo(()=>L.map((x,i)=>[x,i] as const).filter(([x])=>(series==="ALL"||x[3]===series)&&x[4]<=year&&(!q||x[0].toLowerCase().includes(q.toLowerCase()))),[series,year,q]);
 return <div className="app"><header><div className="brand"><div className="logo">◈</div><div><b>TWDU Atlas</b><small>CHRONOLOGY · GEOGRAPHY · CONNECTIONS</small></div></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search locations, characters, communities…"/></header>
 <main><section className="map"><div className="maptitle"><b>{series==="ALL"?"WORLD":S[series].short}</b><span>{visible.length} nodes</span></div><svg viewBox="0 0 100 60"><rect width="100" height="60" fill="#d8d6ce"/><path className="land" d="M7 13 14 9 22 11 27 17 24 23 27 27 22 31 17 28 13 32 8 27 5 22Z"/><path className="land" d="M27 29 31 33 33 41 30 50 26 46 25 38 22 34Z"/><path className="land" d="M45 12 52 8 61 10 67 15 73 14 78 19 76 25 69 27 64 24 59 28 52 25 48 27 44 22Z"/><path className="land" d="M58 28 64 31 66 37 63 44 59 51 55 47 57 40 54 35Z"/><path className="land" d="M75 16 82 14 87 17 91 23 87 28 81 26 78 22Z"/><text x="16" y="36">NORTH AMERICA</text><text x="60" y="6">EUROPE</text>{visible.map(([x,i])=>{const p=project(x[1],x[2]);return <g key={x[0]} className={selected===i?"marker selected":"marker"} transform={`translate(${p.x} ${p.y})`} onClick={()=>setSelected(i)}><circle r="1" fill={S[x[3]].color}/><circle className="halo" r="2.2"/><text x="1.6" y=".4">{x[0]}</text></g>})}</svg>
 <div className="controls"><button onClick={()=>setYear(Math.min(2027,year+1))}>+</button><button onClick={()=>setYear(Math.max(2010,year-1))}>−</button></div>
 <div className="time"><div><span>UNIVERSE TIME</span><b>{year}</b></div><input type="range" min="2010" max="2027" value={year} onChange={e=>setYear(+e.target.value)}/></div>
 <aside className={selected!==null?"sheet open":"sheet"}><div className="grab"/><small>{selected!==null?S[L[selected][3]].name:view.toUpperCase()}</small><h2>{selected!==null?L[selected][0]:view==="map"?"Explore the universe":view==="timeline"?"Universe timeline":view==="people"?"People & connections":"Watch guide"}</h2>
 {selected!==null?<><div className="pills"><i>{L[selected][5]}</i><i>{L[selected][4]}+</i><i>{S[L[selected][3]].short}</i></div><p>{L[selected][6]}</p><button className="primary" onClick={()=>setSelected(null)}>Close location</button></>:
 <>{view==="map"&&<><div className="chips"><button className={series==="ALL"?"active":""} onClick={()=>setSeries("ALL")}>All</button>{Object.entries(S).map(([k,v])=><button key={k} className={series===k?"active":""} onClick={()=>setSeries(k as Key)}>{v.name}</button>)}</div><div className="cards">{visible.map(([x,i])=><article key={i} onClick={()=>setSelected(i)}><small>{S[x[3]].short} · {x[4]}</small><b>{x[0]}</b><span>{x[6]}</span></article>)}</div></>}
 {view==="timeline"&&<div className="cards">{E.filter(x=>x[0]<=year&&(series==="ALL"||x[2]===series)).map(x=><article key={x[1]}><small>{x[0]} · {S[x[2] as Key].short}</small><b>{x[1]}</b></article>)}</div>}
 {view==="people"&&<div className="cards">{["Rick Grimes","Michonne","Daryl Dixon","Negan","Morgan Jones","Jadis"].map(x=><article key={x}><small>CHARACTER NODE</small><b>{x}</b><span>Cross-series appearances and relationships will connect here.</span></article>)}</div>}
 {view==="guide"&&<div className="cards"><article><small>WATCH ORDER</small><b>Episode-level chronology</b><span>Including anthology placement and crossover events.</span></article><article><small>DATA ENGINE</small><b>Canon-backed entities</b><span>Series, seasons, episodes, locations and sources.</span></article></div>}</>}</aside>
 <nav>{(["map","timeline","people","guide"] as const).map(v=><button className={view===v?"active":""} key={v} onClick={()=>{setView(v);setSelected(null)}}>{v==="map"?"⌘":v==="timeline"?"◷":v==="people"?"♙":"▤"}<small>{v}</small></button>)}</nav></section></main></div>
}