import series from "../data/series.json";
import seasons from "../data/seasons.json";
import locations from "../data/locations.json";
import events from "../data/events.json";
import characters from "../data/characters.json";
import communities from "../data/communities.json";
import factions from "../data/factions.json";
import connections from "../data/connections.json";
import watchOrder from "../data/watchOrder.json";
import episodes from "../data/episodes.json";
import seasonMeta from "../data/seasonMeta.json";
import media from "../data/media.json";
import webisodes from "../data/webisodes.json";
import universeEvents from "../data/universeEvents.json";
import characterEpisodes from "../data/characterEpisodes.json";
import locationEpisodes from "../data/locationEpisodes.json";
import connectionEpisodes from "../data/connectionEpisodes.json";

export const atlasData={series,seasons,seasonMeta,locations,events,universeEvents,characters,communities,factions,connections,watchOrder,episodes,webisodes,media,characterEpisodes,locationEpisodes,connectionEpisodes};
export type SeriesKey="TWD"|"FTWD"|"TALES"|"WB"|"OWL"|"DARYL"|"DEAD"|"MORE_TALES";
export type Location=typeof locations[number];
export type Event=typeof events[number];
export type WatchOrderItem=typeof watchOrder[number];
